modLoader = "javafml"
loaderVersion = "[36,)"
license = "Apache-2.0"

[[mods]]
modId = "forgedapifork"
version = "${version}"
displayName = "ForgedAPI (Fork)"
displayURL="https://github.com/shizotoaster/ForgedAPIFork" #optional
logoFile= "forgedapi_fork_icon.png" #optional
logoBlur=false
credits='''

    * FabricMC - Fabric API
''' #optional
authors='''

    * shizotoaster
''' #optional
description = '''
Fabric API unofficial Forge port (fork).

Contains the essentials for Fabric API modules.
'''

[[mods]]
modId = "forgedapi"
version = "0.1.3"
displayName = "ForgedAPI"
displayURL="https://github.com/shizotoaster/ForgedAPIFork" #optional
logoFile= "forgedapi_icon.png" #optional
credits='''

    * FabricMC - Fabric API
''' #optional
authors='''

    * PortingLab
''' #optional
description = '''
Dummy mod providing forgedapi mod id to outdated mods
'''

[[mods]]
modId = "indium"
version = "1.0.0"
displayName = "Indium"
displayURL="https://github.com/shizotoaster/ForgedAPIFork" #optional
logoFile= "indium_icon.png" #optional
authors='''

    * comp500
''' #optional
description = '''
§mSodium§r Embeddium/Rubidium addon providing support for the Fabric Rendering API, based on Indigo
'''

[[dependencies.forgedapi]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.forgedapi]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5]"
ordering = "NONE"
side = "BOTH"
